In [43]:
#Importez les librairies
import numpy as np
import pandas as pd

In [62]:
# Lire le fichier CSV
data = pd.read_csv('Credits_0594.csv', sep=';', header=0, index_col=0)

In [45]:
#Partie A
#Afficher les 5 premières lignes du tableau
data.head(5)

,Revenu_Annuel,Montant_Credit,Durée_Credit,Taux_Interet,Type_Credit,Statut_Credit
ID_Client,,,,,,
C0001,54535,302034,15,4.43,Consommation,Accepté
C0002,28512,107207,15,5.48,Immobilier,Refusé
C0003,19841,67554,10,2.84,Consommation,Accepté
C0004,93528,87282,5,2.50,Consommation,Refusé
C0005,54261,148088,20,4.77,Consommation,Accepté

In [46]:
#Indiquer les dimensions de ce fichier
dim = data.shape
print(dim)

(100, 6)

In [47]:
#Enumérer les colonnes
col = data.columns
print(col)

Index(['Revenu_Annuel', 'Montant_Credit', 'Durée_Credit', 'Taux_Interet',
       'Type_Credit', 'Statut_Credit'],
      dtype='str')

In [48]:
#Spécifier les types de colonnes
t = data.dtypes
print(t)

Revenu_Annuel       int64
Montant_Credit      int64
Durée_Credit        int64
Taux_Interet      float64
Type_Credit           str
Statut_Credit         str
dtype: object

In [49]:
#Accéder aux données du "Type_Credit"
credit = data['Type_Credit'][0:5]
print(credit)

ID_Client
C0001    Consommation
C0002      Immobilier
C0003    Consommation
C0004    Consommation
C0005    Consommation
Name: Type_Credit, dtype: str

In [50]:
#Accéder aux données du "Taux_Interet"
Taux = data['Taux_Interet'][0:5]
print(Taux)

ID_Client
C0001    4.43
C0002    5.48
C0003    2.84
C0004    2.50
C0005    4.77
Name: Taux_Interet, dtype: float64

In [64]:
#Accéder aux données du "Revenu_Annuel" , "Montant_Credit", Durée_Credit"
donne = data[['Revenu_Annuel', 'Montant_Credit', 'Durée_Credit']][0:5]
print(donne)

           Revenu_Annuel  Montant_Credit  Durée_Credit
ID_Client
C0001              54535          302034            15
C0002              28512          107207            15
C0003              19841           67554            10
C0004              93528           87282             5
C0005              54261          148088            20

In [66]:
#Lister les caractéristiques statistiques des variables Revenu_Annuel" et "Montant_Credit"
data[['Revenu_Annuel', 'Montant_Credit']].describe()

       Revenu_Annuel  Montant_Credit
count     100.000000      100.000000
mean    54859.070000   287293.540000
std     23791.660473   137069.994499
min     15104.000000     7451.000000
25%     34481.750000   188506.750000
50%     51496.500000   302476.000000
75%     73638.000000   395726.250000
max     99146.000000   499561.000000

In [65]:
#Pensez-vous qu’il y a plus Statut_Credit accepte ou refusé ?
df = pd.DataFrame(data)
print(df['Statut_Credit'].value_counts())

Statut_Credit
Refusé     51
Accepté    49
Name: count, dtype: int64

In [67]:
#Pensez-vous qu’il y a plus Statut_Credit accepte ou refusé ? Analyser en %
print(df['Statut_Credit'].value_counts(normalize=True) * 100)

Statut_Credit
Refusé     51.0
Accepté    49.0
Name: proportion, dtype: float64

In [68]:
#Enumérer la première valeur de « Type_Credit »
print(data['Type_Credit'].iloc[0])

Consommation

In [69]:
#Enumérer les 4 premières valeurs du Durée_Credit
print(data['Durée_Credit'].iloc[0:4])

ID_Client
C0001    15
C0002    15
C0003    10
C0004     5
Name: Durée_Credit, dtype: int64

In [70]:
#Trier les valeurs du « Taux_Interet » du plus petit au plus grand
df.sort_values(by='Taux_Interet', ascending=True).head(5)

,Revenu_Annuel,Montant_Credit,Durée_Credit,Taux_Interet,Type_Credit,Statut_Credit
ID_Client,,,,,,
C0034,84478,394265,15,1.54,Auto,Accepté
C0032,33593,199078,20,1.57,Consommation,Accepté
C0066,51250,96072,20,1.60,Auto,Accepté
C0089,17624,7451,25,1.64,Consommation,Refusé
C0063,47631,341843,25,1.70,Consommation,Refusé

In [73]:
#Partie B
#Créer une nouvelle colonne dans le dataFrame initiale afin de calculer le montant du crédit par année (diviser le montant du crédit par la durée du crédit)
df['Montant_Credit_Annuel'] = df['Montant_Credit'] / df['Durée_Credit']
print(df.iloc[0])

Revenu_Annuel                   54535
Montant_Credit                 302034
Durée_Credit                       15
Taux_Interet                     4.43
Type_Credit              Consommation
Statut_Credit                 Accepté
Montant_Credit_Annuel         20135.6
Name: C0001, dtype: object

In [74]:
#Afficher les données où le montant crédit est > 13 000€ par an
print(df[df['Montant_Credit_Annuel'] > 13000])

           Revenu_Annuel  Montant_Credit  Durée_Credit  Taux_Interet  \
ID_Client
C0001              54535          302034            15          4.43
C0004              93528           87282             5          2.50
C0008              69729          386621             5          2.74
C0009              54627          367497            10          4.13
C0012              64725          421507             5          2.84
...                  ...             ...           ...           ...
C0094              86256          302918            10          2.21
C0095              34420          182235            10          1.78
C0096              64805          178598             5          3.60
C0098              90997          351522            25          3.59
C0099              46114          223449            15          3.57

            Type_Credit Statut_Credit  Montant_Credit_Annuel
ID_Client
C0001      Consommation       Accepté               20135.60
C0004      Consommation        Refusé               17456.40
C0008        Immobilier       Accepté               77324.20
C0009      Consommation       Accepté               36749.70
C0012        Immobilier        Refusé               84301.40
...                 ...           ...                    ...
C0094      Consommation       Accepté               30291.80
C0095              Auto        Refusé               18223.50
C0096        Immobilier       Accepté               35719.60
C0098      Consommation        Refusé               14060.88
C0099              Auto        Refusé               14896.60

[66 rows x 7 columns]

In [75]:
#Afficher les valeurs du montant_annuel trié par ordre croissant
print(df.sort_values(by='Montant_Credit_Annuel', ascending=True).head(5))

           Revenu_Annuel  Montant_Credit  Durée_Credit  Taux_Interet  \
ID_Client
C0089              17624            7451            25          1.64
C0073              69196           12945            25          3.53
C0100              29029           52149            25          2.68
C0088              96501           42648            20          2.39
C0061              48897           56046            15          4.26

            Type_Credit Statut_Credit  Montant_Credit_Annuel
ID_Client
C0089      Consommation        Refusé                 298.04
C0073              Auto        Refusé                 517.80
C0100        Immobilier       Accepté                2085.96
C0088              Auto        Refusé                2132.40
C0061              Auto       Accepté                3736.40