# Learning Objectives

Understand the dataset, 
Data preprocessing - Cleaning and Cleansing and 
Data analysis

# Data importation

In [108]:
# 1. Load the Dataset Titanic built-in in python
import seaborn as sns
titanic = sns.load_dataset('titanic')

In [109]:
# 2. get the size of the dataset
titanic.shape

(891, 15)

In [110]:
#Show the first 5 rows
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [111]:
#Show the last 5 rows
titanic.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [112]:
# get the info of the dataset
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

# Data Preprocessing

In [113]:
#check missing values
titanic.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [114]:
# manage missing values as you see pertinent
titanic = titanic.dropna(subset=['deck'])

In [115]:
#check missing values
titanic.isna().sum()

survived        0
pclass          0
sex             0
age            19
sibsp           0
parch           0
fare            0
embarked        2
class           0
who             0
adult_male      0
deck            0
embark_town     2
alive           0
alone           0
dtype: int64

In [116]:
# manage missing values as you see pertinent
titanic = titanic.fillna({'age': titanic['age'].median(), 'embarked': titanic['embarked'].mode()})

In [117]:
# manage missing values as you see pertinent
titanic.isna().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
who            0
adult_male     0
deck           0
embark_town    2
alive          0
alone          0
dtype: int64

In [118]:
# manage missing values as you see pertinent
titanic = titanic.dropna(subset=['embark_town'])

In [119]:
#check missing values
titanic.isna().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [120]:
# Check for duplicate rows
titanic.duplicated().sum()

np.int64(1)

In [121]:
#Drop duplicates keeping the first occurance
titanic = titanic.drop_duplicates(keep='first')

In [122]:
# Check for duplicate rows
titanic.duplicated().sum()

np.int64(0)

In [123]:
#show the final dataset 5 first rows
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True

1. Which columns are numerical? Which are categorical?

# Data Analysis

In [124]:
#Is there more people alive or dead ? Intepret in %
titanic['alive'].value_counts(normalize=True) * 100

alive
yes    66.5
no     33.5
Name: proportion, dtype: float64

In [125]:
#group survival status (alive) by embarkation town (embark_town) and calculate both counts and percentages.
titanic.groupby('embark_town')['alive'].value_counts()

embark_town  alive
Cherbourg    yes      51
             no       17
Queenstown   no        2
             yes       2
Southampton  yes      80
             no       48
Name: count, dtype: int64

In [126]:
#The question but in %
titanic.groupby('embark_town')['alive'].value_counts(normalize=True) * 100

embark_town  alive
Cherbourg    yes      75.0
             no       25.0
Queenstown   no       50.0
             yes      50.0
Southampton  yes      62.5
             no       37.5
Name: proportion, dtype: float64

In [127]:
#How many classes do we have ?
titanic['class'].nunique()

3

In [128]:
#Enumerate the different classes
titanic['class'].unique()

['First', 'Third', 'Second']
Categories (3, str): ['First', 'Second', 'Third']

In [129]:
#Is there more man or women embarked in the Titanic. Count the number of men and number of women
titanic['sex'].value_counts()

sex
male      106
female     94
Name: count, dtype: int64

In [130]:
#analyse your results in %
titanic['sex'].value_counts(normalize=True) * 100

sex
male      53.0
female    47.0
Name: proportion, dtype: float64

In [131]:
#What is the maximum age and the minimum age of people embarked ?

In [132]:
#What is the maximum age and the minimum age of people embarked ?
#min
print("age min :",titanic['age'].min())

age min : 0.92

In [133]:
#max
print("age max :",titanic['age'].max())

age max : 80.0

In [148]:
#What is the average age ?
print("age moyen :",titanic['age'].mean())

age mean : 35.7171

In [149]:
#How many embark_town are they ?
titanic['embark_town'].nunique()

3

In [152]:
##List the embarked towns
titanic['embark_town'].unique()

Embarked towns: <StringArray>
['Cherbourg', 'Southampton', 'Queenstown']
Length: 3, dtype: str

### Indexing

### Using .loc[] (Label-based indexing)

In [153]:
#Select all information about the passenger at index 0.
titanic.loc[titanic.index[0]]

survived               1
pclass                 1
sex               female
age                 38.0
sibsp                  1
parch                  0
fare             71.2833
embarked               C
class              First
who                woman
adult_male         False
deck                   C
embark_town    Cherbourg
alive                yes
alone              False
Name: 1, dtype: object

In [161]:
#Select all information about the passenger at index 50.
titanic.loc[titanic.index[50]]

survived                 0
pclass                   1
sex                   male
age                   52.0
sibsp                    1
parch                    1
fare                 79.65
embarked                 S
class                First
who                    man
adult_male            True
deck                     E
embark_town    Southampton
alive                   no
alone                False
Name: 262, dtype: object

In [157]:
#Get the sex and age of the passenger at index 10.
titanic.loc[10, ['sex', 'age']]

sex    female
age       4.0
Name: 10, dtype: object

In [164]:
#Select passengers from index 100 to 105 and show only their survived and pclass columns.
titanic.loc[100:105, ['survived', 'pclass']]

     survived  pclass
102         0       1

In [166]:
#Get all passengers who embarked from "Southampton" and display only sex, age, and fare
titanic.loc[titanic['embark_town'] == 'Southampton', ['sex', 'age', 'fare']]

        sex   age     fare
3    female  35.0  53.1000
6      male  54.0  51.8625
10   female   4.0  16.7000
11   female  58.0  26.5500
21     male  34.0  13.0000
..      ...   ...      ...
862  female  48.0  25.9292
867    male  31.0  50.4958
871  female  47.0  52.5542
872    male  33.0   5.0000
887  female  19.0  30.0000

[128 rows x 3 columns]

In [169]:
#Select the first 5 female passengers and display their age, pclass, and survived.
titanic.loc[titanic['sex'] == 'female', ['age', 'pclass', 'survived']].head(5)

     age  pclass  survived
1   38.0       1         1
3   35.0       1         1
10   4.0       3         1
11  58.0       1         1
31  36.0       1         1

### Using .iloc[] (Position-based indexing)

In [167]:
#Display the first row of the dataset.
titanic.iloc[0]

survived               1
pclass                 1
sex               female
age                 38.0
sibsp                  1
parch                  0
fare             71.2833
embarked               C
class              First
who                woman
adult_male         False
deck                   C
embark_town    Cherbourg
alive                yes
alone              False
Name: 1, dtype: object

In [172]:
#Get the values of age and fare for the 5th passenger (row index 4).
titanic.iloc[4, [3, 6]]

age     58.00
fare    26.55
Name: 11, dtype: float64

In [173]:
#Display the first 10 passengers (rows 0–9) but only the first 3 columns (survived, pclass, sex).
titanic.iloc[0:10, 0:3]

    survived  pclass     sex
1          1       1  female
3          1       1  female
6          0       1    male
10         1       3  female
11         1       1  female
21         1       2    male
23         1       1    male
27         0       1    male
31         1       1  female
52         1       1  female